detector:
  cfg: 'FCOS'
  mode: 'training'
  generator:
    cfg: 'TargetGenerator'
    strides: [8, 16, 32, 64, 128]
    limit_range: [[-1, 64], [64, 128], [128, 256], [256, 512], [512, 999999]]
  encoder:
    backbone_:
      cfg: 'resnet50'
      pretrained: False
      include_top: False
      out_indices: [3, 4, 5]
      norm: 'BN'
    neck_:
      cfg: 'FPN'
      out_channel: 256
      use_p5: True
    head_:
      cfg: 'FCOSHead'
      num_classes: 25
      stacked_convs: 4
      feat_channels: 256
      prior: 0.01
      cnt_on_reg: True
      norm: 'GN'
    loss_:
      cfg: 'fcos_loss'
      cls_loss:
        cfg: 'focal_loss'
        alpha: 0.25
        gamma: 2.0
      reg_loss:
        cfg: 'smooth_l1'
      cnt_loss:
        cfg: 'ce'
  decoder:
    score_thres: 0.3
    nms_iou_thres: 0.7
    max_detection: 300
    add_centerness: True

optimizer:
  cfg: 'Adam'
  lr: 0.001
#  momentum: 0.9
#  weight_decay: 0.0001

dataset_train:
      cfg: 'VOCDataset'
      batch_size: 4
      img_sizes: [480, 640]
      train_set: "[('2007', 'trainval_mini')]"
      root_dir: 'H:/DataSets/VOCdevkit0712/VOCdevkit'
      is_train: True

dataset_eval:
      cfg: 'VOCDataset'
      batch_size: 1
      img_sizes: [480, 640]
      train_set: "[('2007', 'test_mini')]"
      root_dir: 'H:/DataSets/VOCdevkit0712/VOCdevkit'
      is_train: False
