detector:
  cfg: 'RetinaNet'
  mode: 'training'
  generator:
    cfg: 'Horizontal_Generator'
    ratios: [0.5, 1, 2]
    scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
    strides: [8, 16, 32, 64, 128]
    sizes: [32, 64, 128, 256, 512]
  encoder:
    backbone_:
      cfg: 'resnet50'
      pretrained: False
      include_top: False
      out_indices: [3, 4, 5]
      norm: 'BN'
    neck_:
      cfg: 'FPN'
      out_channel: 256
      use_p5: True
    head_:
      cfg: 'RetinaHead'
      num_classes: 25
      feat_channels: 256
      num_anchors: 9
      prior: 0.01
      norm: 'BN'
    loss_:
      cfg: 'retina_loss'
      cls_loss:
        cfg: 'focal_loss'
        alpha: 0.25
        gamma: 2.0
      reg_loss:
        cfg: 'smooth_l1'
  decoder:
    score_thres: 0.3
    nms_iou_thres: 0.7
    max_detection: 300

optimizer:
  cfg: 'SGD'
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0001

dataset_train:
      cfg: 'VOCDataset'
      batch_size: 4
      img_sizes: [480, 640]
      train_set: "[('2007', 'trainval')]"
      root_dir: 'H:/DataSets/VOCdevkit0712/VOCdevkit'
      is_train: False

dataset_eval:
      cfg: 'VOCDataset'
      batch_size: 1
      img_sizes: [480, 640]
      train_set: "[('2007', 'test')]"
      root_dir: 'H:/DataSets/VOCdevkit0712/VOCdevkit'
      is_train: False
